//! Static-site renderer. One file per item + an index.

use std::fmt::Write as _;
use std::path::Path;

use crate::extract::DocSet;
use crate::DocError;

const STYLE: &str = r#"
body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; color: #1f2328; }
h1, h2 { color: #0969da; }
nav { font-size: 0.9rem; }
.kind { color: #6e7781; font-weight: normal; font-size: 0.9rem; }
ul.items { list-style: none; padding: 0; }
ul.items li { padding: 0.4rem 0; border-bottom: 1px solid #d8dee4; }
.doc { margin-top: 1rem; white-space: pre-wrap; }
"#;

pub fn write_site(title: &str, docset: &DocSet, out_dir: &Path) -> Result<(), DocError> {
    std::fs::create_dir_all(out_dir).map_err(|source| DocError::Io {
        path: out_dir.to_path_buf(),
        source,
    })?;

    // index.html
    let index_path = out_dir.join("index.html");
    let mut index = String::new();
    write_html_open(&mut index, &format!("{title} – kiln docs"));
    let _ = writeln!(index, "<h1>{}</h1>", html_escape(title));
    let _ = writeln!(index, "<p>Generated by <code>kiln doc</code>.</p>");
    if docset.items.is_empty() {
        let _ = writeln!(index, "<p>No documented items found.</p>");
    } else {
        let _ = writeln!(index, "<ul class=\"items\">");
        for item in docset.items.values() {
            let _ = writeln!(
                index,
                "<li><a href=\"{name}.html\">{name}</a> <span class=\"kind\">{kind}</span></li>",
                name = html_escape(&item.name),
                kind = item.kind.as_str()
            );
        }
        let _ = writeln!(index, "</ul>");
    }
    write_html_close(&mut index);
    write_file(&index_path, &index)?;

    // Per-item pages.
    for item in docset.items.values() {
        let path = out_dir.join(format!("{}.html", item.name));
        let mut s = String::new();
        write_html_open(&mut s, &format!("{} – {}", item.name, title));
        let _ = writeln!(
            s,
            "<nav><a href=\"index.html\">{}</a> &rsaquo; {}</nav>",
            html_escape(title),
            html_escape(&item.name)
        );
        let _ = writeln!(
            s,
            "<h1>{} <span class=\"kind\">{}</span></h1>",
            html_escape(&item.name),
            item.kind.as_str()
        );
        if !item.doc.is_empty() {
            let _ = writeln!(s, "<div class=\"doc\">{}</div>", html_escape(&item.doc));
        } else {
            let _ = writeln!(s, "<p><em>No documentation.</em></p>");
        }
        if let Some(p) = &item.source_file {
            let _ = writeln!(
                s,
                "<p style=\"font-size: 0.85rem; color: #6e7781\">Source: {}</p>",
                html_escape(&p.display().to_string())
            );
        }
        write_html_close(&mut s);
        write_file(&path, &s)?;
    }

    Ok(())
}

fn write_html_open(s: &mut String, title: &str) {
    let _ = writeln!(s, "<!DOCTYPE html>");
    let _ = writeln!(s, "<html lang=\"en\">");
    let _ = writeln!(s, "<head>");
    let _ = writeln!(s, "<meta charset=\"utf-8\">");
    let _ = writeln!(
        s,
        "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
    );
    let _ = writeln!(s, "<title>{}</title>", html_escape(title));
    let _ = writeln!(s, "<style>{STYLE}</style>");
    let _ = writeln!(s, "</head>");
    let _ = writeln!(s, "<body>");
}

fn write_html_close(s: &mut String) {
    let _ = writeln!(s, "</body>");
    let _ = writeln!(s, "</html>");
}

fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

fn write_file(path: &Path, body: &str) -> Result<(), DocError> {
    std::fs::write(path, body).map_err(|source| DocError::Io {
        path: path.to_path_buf(),
        source,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::extract::{DocItem, ItemKind};
    use std::path::PathBuf;

    #[test]
    fn writes_index_and_per_item_pages() {
        let tmp = tempfile::tempdir().unwrap();
        let mut docset = DocSet::default();
        docset.items.insert(
            "counter".to_string(),
            DocItem {
                name: "counter".into(),
                kind: ItemKind::Module,
                doc: "A 4-bit counter.".into(),
                source_file: Some(PathBuf::from("/proj/src/counter.sv")),
            },
        );
        docset.items.insert(
            "my_pkg".to_string(),
            DocItem {
                name: "my_pkg".into(),
                kind: ItemKind::Package,
                doc: "Shared types.".into(),
                source_file: None,
            },
        );
        write_site("hello", &docset, tmp.path()).unwrap();
        let index = std::fs::read_to_string(tmp.path().join("index.html")).unwrap();
        assert!(index.contains("<!DOCTYPE html>"));
        assert!(index.contains("counter"));
        assert!(index.contains("my_pkg"));
        // Cross-references: index → item pages.
        assert!(index.contains("href=\"counter.html\""));
        assert!(index.contains("href=\"my_pkg.html\""));
        let counter = std::fs::read_to_string(tmp.path().join("counter.html")).unwrap();
        assert!(counter.contains("A 4-bit counter."));
        assert!(counter.contains("href=\"index.html\""));
    }

    #[test]
    fn empty_docset_writes_index_with_placeholder() {
        let tmp = tempfile::tempdir().unwrap();
        let docset = DocSet::default();
        write_site("hello", &docset, tmp.path()).unwrap();
        let index = std::fs::read_to_string(tmp.path().join("index.html")).unwrap();
        assert!(index.contains("No documented items"));
    }

    #[test]
    fn html_escape_handles_special_chars() {
        assert_eq!(html_escape("a & b < c > d"), "a &amp; b &lt; c &gt; d");
    }
}
